[general]
import = [
  "~/.config/alacritty/themes/themes/github_light.toml"
]

[window]

padding.x = 8
padding.y = 8

decorations = "None"

[font]

normal.family = "PlemolJP Console NF"
bold.family = "PlemolJP Console NF"
italic.family = "PlemolJP Console NF"
bold_italic.family = "PlemolJP Console NF"

normal.style = "Medium"
bold.style = "Bold"
italic.style = "Medium Italic"
bold_italic.style = "Bold Italic"

size = 12.0
offset.y = 4
offset.x = 2
